### ISSUE TITLE
Install Syntax Error

### ISSUE THREAD

**Issue by Kevinario** [nodecg/generator-nodecg#13]
I was unable to use *yo nodecg* , due to a syntax error present at line 61 of: generators/app/index.js : 
> }, this).then(function (**{**name**}**) {

The bold curly brackets were given as the cause.

Edit: Sorry, it seems the install worked when i upgraded my node from version 4 to the latest.

**Comment by Lange** [comment]
What version of Node.js are you on? I think you need to be on v6 or higher.

**Comment by Kevinario** [comment]
Oh dind't see your reply when making the edit, but i already fixed it by updating to v6 yes.
