### ISSUE TITLE
No valid versions available for generator-nodecg

### ISSUE THREAD

**Issue by gorbeia** [nodecg/generator-nodecg#72]
I have been unable to install  the generator using the documented command.

```
$ npm install generator-nodecg
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for generator-nodecg

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/inaki/.npm/_logs/2021-02-14T14_54_25_234Z-debug.log
```

It seems that it is not published to npm.

I have been able to install it running
`
npm install https://github.com/nodecg/generator-nodecg`

**Comment by alvancamp** [comment]
Fixed some time ago.
